---
data:
  train:
    source: 'csv'
    args:
      filepath: '../data/twitter_training.csv'
      seperator: ','
    text-column: 3
    label-column: 2
  test: null
    # source:
    #   - 'CSV'
    #   - 'filepath'
    #   - ','
    # text-column: null
    # label-column: null
model:
  class: 'BOW.Linear_ensemble'
  save-dir: '../export/'
  args:
    vectorizer-type: 'tfidf'
    vectorizer-max-features: 10000
    vectorizer-ngrams: 
      - 1 #min
      - 1 #max
    clf-penalty: 'none'
    clf-max-iter: 10000
    clf-solver: 'lbfgs'
    ensemble-groups: 10
    ensemble-folds: 8
    scale-inputs: true

# model:
#   class: 'BOW.Linear_ensemble_sgd'
#   args:
#     vectorizer-type: 'tfidf'
#     vectorizer-max-features: 10000
#     vectorizer-ngrams: 
#       - 1 #min
#       - 1 #max
#     clf-penalty: 'none'
#     clf-max-iter: 10000
#     clf-loss: 'log_loss'
#     clf-early-stop: True
#     ensemble-groups: 10
#     ensemble-folds: 8
#     scale-inputs: true
    

preprocessing:
  remove-garbage-words: true
  remove-numbers: true
  remove-stopwords: false
  lemmatize: false
  force-lower-case: true
  core-words: null