---
data:
  read:
    class: 'flat.Delimited_file'
    text-column: '3'
    shuffle: true
    fraction: 0.01
    remove-null-text: true
    args:
      filepath: '../data/twitter_training.csv'
      seperator: ','
  
  write:
    class: 'flat.Delimited_file'
    label-column: '12'
    args:
      filepath: '../data/twitter_pred.csv'
      seperator: ','

model:
  path: '../export/1669250183'
