---
data:
  read:
    source-class: 'flat.Delimited_file'
    text-column: '3'
    shuffle: true
    fraction: 0.01
    remove-null-text: true
    args:
      filepath: '../data/twitter_training.csv'
      seperator: ','
  
  write:
    source-class: 'flat.Delimited_file'
    text-column: '3'
    label-column: '2'
    args:
      filepath: '../data/twitter_pred.csv'
      seperator: ','

model:
  yml-path: '../export/1668670743.yml'
